version: '3.8'
services:
  wordpress:
    build: .
    ports:
      - "8080:80"
    volumes:
      - wordpress-data:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: wordpress-db.c3mw22cmyg5j.ap-south-1.rds.amazonaws.com:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: Navin3322
      WORDPRESS_DB_NAME: wordpress

volumes:
  wordpress-data:
